// General
export const LOGOUT = 'LOGOUT';
export const SET_GUILD = 'SET_GUILD';
export const SET_GUILD_POST_SUCCESS = 'SET_GUILD_POST_SUCCESS';
export const SET_GUILD_POST_FAILURE = 'SET_GUILD_POST_FAILURE'

// BotGuilds
export const SET_BOT_GUILDS_SUCCESS = 'SET_BOT_GUILDS_SUCCESS';
export const SET_BOT_GUILDS_FAILURE = 'SET_BOT_GUILDS_FAILURE';
export const SET_GUILD_PREFIX = 'SET_GUILD_PREFIX';
export const REGISTER_GUILD = 'REGISTER_GUILD';

// DiscordGuilds
export const SET_DISCORD_GUILDS_SUCCESS = 'SET_DISCORD_GUILDS_SUCCESS';
export const SET_DISCORD_GUILDS_FAILURE = 'SET_DISCORD_GUILDS_FAILURE';

// Client
export const SET_OAUTH_CODE = 'SET_OAUTH_CODE';
export const SET_CURRENT_GUILD = 'SET_CURRENT_GUILD';

// User
export const FETCH_USER = 'FETCH_USER';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_FAILURE = 'SET_USER_FAILURE';

// Plugins
export const DISABLE_PLUGIN = 'DISABLE_PLUGIN';
export const ENABLE_PLUGIN = 'ENABLE_PLUGIN';
export const SET_GUILD_PLUGIN_SUCCESS = 'SET_GUILD_PLUGIN_SUCCESS';
export const SET_GUILD_PLUGIN_FAILURE = 'SET_GUILD_PLUGIN_FAILURE';
